"""
Language Pack — Multi-language UI strings and question sets
Add a new language by adding a new key to LANGUAGES dict.
"""

LANGUAGES = {
    "English": {
        "title":        "LIE DETECTOR PRO  ◈  ULTIMATE EDITION",
        "calibrate":    "CALIBRATE",
        "ask":          "ASK ▶",
        "end":          "END ■",
        "save":         "SAVE",
        "status_live":  "● LIVE — click CALIBRATE",
        "status_cal":   "● CALIBRATING",
        "status_ready": "● READY",
        "status_det":   "● DETECTING",
        "cal_prompt":   "CALIBRATING {pct}% — speak naturally",
        "ready_prompt": "READY — select a question",
        "begin_prompt": "CLICK CALIBRATE TO BEGIN",
        "emotion_lbl":  "EMOTION DETECTION",
        "waveform_lbl": "VOICE WAVEFORM",
        "pulse_lbl":    "PULSE SIGNAL (rPPG)",
        "metrics_lbl":  "LIVE METRICS",
        "timeline_lbl": "SCORE TIMELINE (30s)",
        "results_lbl":  "QUESTION RESULTS",
        "hr_lbl":       "HEART RATE",
        "add_q_btn":    "+ ADD",
        "custom_q_ph":  "Type a custom question...",
        "alert_title":  "⚠ DECEPTION ALERT",
        "alert_msg":    "High stress signals detected!",
        "saved_msg":    "Report saved:\n{path}",
        "not_ready":    "Please calibrate first!",
        "no_question":  "Please select or type a question.",
        "questions": [
            "What is your full name?",
            "Are you currently employed?",
            "Have you ever stolen anything?",
            "Do you exercise regularly?",
            "Have you lied to someone today?",
            "Do you enjoy your current job?",
            "Have you ever cheated on a test?",
            "Are you happy right now?",
            "Have you ever betrayed someone's trust?",
            "Do you have any secrets you're hiding?",
        ],
    },

    "हिन्दी (Hindi)": {
        "title":        "झूठ पकड़ने वाला PRO  ◈  अल्टीमेट",
        "calibrate":    "कैलिब्रेट",
        "ask":          "पूछें ▶",
        "end":          "समाप्त ■",
        "save":         "सहेजें",
        "status_live":  "● चालू — कैलिब्रेट करें",
        "status_cal":   "● कैलिब्रेशन",
        "status_ready": "● तैयार",
        "status_det":   "● जांच जारी",
        "cal_prompt":   "कैलिब्रेशन {pct}% — सामान्य रूप से बोलें",
        "ready_prompt": "तैयार — प्रश्न चुनें",
        "begin_prompt": "शुरू करने के लिए कैलिब्रेट करें",
        "emotion_lbl":  "भावना पहचान",
        "waveform_lbl": "आवाज़ तरंग",
        "pulse_lbl":    "नाड़ी संकेत (rPPG)",
        "metrics_lbl":  "लाइव मेट्रिक्स",
        "timeline_lbl": "स्कोर टाइमलाइन (30s)",
        "results_lbl":  "प्रश्न परिणाम",
        "hr_lbl":       "हृदय गति",
        "add_q_btn":    "+ जोड़ें",
        "custom_q_ph":  "अपना प्रश्न लिखें...",
        "alert_title":  "⚠ झूठ अलर्ट",
        "alert_msg":    "उच्च तनाव संकेत मिले!",
        "saved_msg":    "रिपोर्ट सहेजी:\n{path}",
        "not_ready":    "पहले कैलिब्रेट करें!",
        "no_question":  "कृपया एक प्रश्न चुनें।",
        "questions": [
            "आपका पूरा नाम क्या है?",
            "क्या आप अभी नौकरी करते हैं?",
            "क्या आपने कभी कुछ चुराया है?",
            "क्या आप नियमित व्यायाम करते हैं?",
            "क्या आपने आज किसी से झूठ बोला?",
            "क्या आप अपनी नौकरी से खुश हैं?",
            "क्या आपने कभी परीक्षा में नकल की?",
            "क्या आप अभी खुश हैं?",
            "क्या आपने कभी किसी का विश्वास तोड़ा?",
            "क्या आप कोई राज छुपा रहे हैं?",
        ],
    },

    "বাংলা (Bengali)": {
        "title":        "মিথ্যা ধরার যন্ত্র PRO  ◈  আলটিমেট",
        "calibrate":    "ক্যালিব্রেট",
        "ask":          "জিজ্ঞেস করুন ▶",
        "end":          "শেষ করুন ■",
        "save":         "সংরক্ষণ",
        "status_live":  "● চালু — ক্যালিব্রেট করুন",
        "status_cal":   "● ক্যালিব্রেশন",
        "status_ready": "● প্রস্তুত",
        "status_det":   "● পরীক্ষা চলছে",
        "cal_prompt":   "ক্যালিব্রেশন {pct}% — স্বাভাবিকভাবে কথা বলুন",
        "ready_prompt": "প্রস্তুত — প্রশ্ন বেছে নিন",
        "begin_prompt": "শুরু করতে ক্যালিব্রেট করুন",
        "emotion_lbl":  "আবেগ সনাক্তকরণ",
        "waveform_lbl": "কণ্ঠস্বর তরঙ্গ",
        "pulse_lbl":    "নাড়ি সংকেত (rPPG)",
        "metrics_lbl":  "লাইভ মেট্রিক্স",
        "timeline_lbl": "স্কোর টাইমলাইন (৩০স)",
        "results_lbl":  "প্রশ্নের ফলাফল",
        "hr_lbl":       "হৃদস্পন্দন",
        "add_q_btn":    "+ যোগ করুন",
        "custom_q_ph":  "নিজের প্রশ্ন লিখুন...",
        "alert_title":  "⚠ মিথ্যা সতর্কতা",
        "alert_msg":    "উচ্চ চাপের সংকেত পাওয়া গেছে!",
        "saved_msg":    "রিপোর্ট সংরক্ষিত:\n{path}",
        "not_ready":    "আগে ক্যালিব্রেট করুন!",
        "no_question":  "একটি প্রশ্ন বেছে নিন।",
        "questions": [
            "আপনার পুরো নাম কী?",
            "আপনি কি এখন চাকরি করছেন?",
            "আপনি কি কখনো কিছু চুরি করেছেন?",
            "আপনি কি নিয়মিত ব্যায়াম করেন?",
            "আপনি কি আজ কারো সাথে মিথ্যা বলেছেন?",
            "আপনি কি আপনার কাজ উপভোগ করেন?",
            "আপনি কি কখনো পরীক্ষায় নকল করেছেন?",
            "আপনি কি এখন খুশি?",
            "আপনি কি কখনো কারো বিশ্বাস ভেঙেছেন?",
            "আপনি কি কোনো গোপন কথা লুকাচ্ছেন?",
        ],
    },

    "Español": {
        "title":        "DETECTOR DE MENTIRAS PRO  ◈  ULTIMATE",
        "calibrate":    "CALIBRAR",
        "ask":          "PREGUNTAR ▶",
        "end":          "TERMINAR ■",
        "save":         "GUARDAR",
        "status_live":  "● EN VIVO — calibrar",
        "status_cal":   "● CALIBRANDO",
        "status_ready": "● LISTO",
        "status_det":   "● DETECTANDO",
        "cal_prompt":   "CALIBRANDO {pct}% — hable normalmente",
        "ready_prompt": "LISTO — seleccione una pregunta",
        "begin_prompt": "CALIBRE PARA COMENZAR",
        "emotion_lbl":  "DETECCIÓN DE EMOCIÓN",
        "waveform_lbl": "FORMA DE ONDA",
        "pulse_lbl":    "SEÑAL DE PULSO (rPPG)",
        "metrics_lbl":  "MÉTRICAS EN VIVO",
        "timeline_lbl": "LÍNEA DE TIEMPO (30s)",
        "results_lbl":  "RESULTADOS",
        "hr_lbl":       "FRECUENCIA CARDÍACA",
        "add_q_btn":    "+ AGREGAR",
        "custom_q_ph":  "Escribe una pregunta...",
        "alert_title":  "⚠ ALERTA DE ENGAÑO",
        "alert_msg":    "¡Señales de alto estrés detectadas!",
        "saved_msg":    "Reporte guardado:\n{path}",
        "not_ready":    "¡Calibre primero!",
        "no_question":  "Seleccione una pregunta.",
        "questions": [
            "¿Cuál es su nombre completo?",
            "¿Está actualmente empleado?",
            "¿Ha robado algo alguna vez?",
            "¿Hace ejercicio regularmente?",
            "¿Le ha mentido a alguien hoy?",
            "¿Disfruta su trabajo actual?",
            "¿Ha copiado en un examen?",
            "¿Está feliz ahora mismo?",
            "¿Ha traicionado la confianza de alguien?",
            "¿Está ocultando algún secreto?",
        ],
    },

    "中文 (Chinese)": {
        "title":        "测谎仪 PRO  ◈  终极版",
        "calibrate":    "校准",
        "ask":          "提问 ▶",
        "end":          "结束 ■",
        "save":         "保存",
        "status_live":  "● 实时 — 点击校准",
        "status_cal":   "● 校准中",
        "status_ready": "● 准备就绪",
        "status_det":   "● 检测中",
        "cal_prompt":   "校准中 {pct}% — 请正常说话",
        "ready_prompt": "准备就绪 — 选择问题",
        "begin_prompt": "点击校准开始",
        "emotion_lbl":  "情绪检测",
        "waveform_lbl": "声音波形",
        "pulse_lbl":    "脉搏信号 (rPPG)",
        "metrics_lbl":  "实时数据",
        "timeline_lbl": "评分时间轴 (30秒)",
        "results_lbl":  "问题结果",
        "hr_lbl":       "心率",
        "add_q_btn":    "+ 添加",
        "custom_q_ph":  "输入自定义问题...",
        "alert_title":  "⚠ 欺骗警报",
        "alert_msg":    "检测到高压力信号！",
        "saved_msg":    "报告已保存:\n{path}",
        "not_ready":    "请先校准！",
        "no_question":  "请选择一个问题。",
        "questions": [
            "你的全名是什么？",
            "你目前有工作吗？",
            "你曾经偷过东西吗？",
            "你经常锻炼吗？",
            "你今天对某人说谎了吗？",
            "你喜欢你现在的工作吗？",
            "你曾经在考试中作弊吗？",
            "你现在快乐吗？",
            "你曾经背叛过别人的信任吗？",
            "你在隐瞒什么秘密吗？",
        ],
    },
}

DEFAULT_LANG = "English"


def get_lang(name):
    return LANGUAGES.get(name, LANGUAGES[DEFAULT_LANG])


def available_languages():
    return list(LANGUAGES.keys())
